title:              Port to Port Property Maintenance & Lawn Care
email:              dave@porttoport.ca
address:            "7294 NS-366, Northport, NS B0L 1E0"
phone_number:       (506)-540-0207
description:        Servicing Port Elgin, Tidnish, Northport, Pugwash, Wallace and surrounding areas!
author:             David Thomas
baseurl:            ""
url:                "https://www.porttoport.ca"

pin_location: "https://maps.app.goo.gl/nx8BK1oADZcFpxBW8"
social_profiles:
  facebook:  Port-To-Port-Property-Maintenance-Lawn-Care-61569891131400
  instagram: porttoport

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-6K0FGM8G6X

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-gallery-generator

gallery:
  dir: services # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Our Services"    # Title for gallery index page
  title_prefix: "Our Services: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    concrete:
      best_image: default.jpg
      info:
        desc: "Concrete slabs, footings, ICF, building leveling, hearths and more."
    roofing:
      best_image: default.jpg
      info:
        desc: "Asphalt roofs, steel, or rubber, we do them all."
    carpentry:
      best_image: default.jpg
      info:
        desc: "Decks, gazebos, complete new builds, additions or extensions."
